default: &default
  adapter: redis
  url: <%= ENV.fetch "REDIS_QUEUE_URL", "redis://localhost:6379/1" %>

development:
  <<: *default
  channel_prefix: todo_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch "REDIS_QUEUE_URL", "redis://localhost:6379/1" %>
  channel_prefix: todo_production
